// apps/qwik/src/components/ItemList.tsx
import { component$ } from '@builder.io/qwik';
import { ItemCard } from './ItemCard';
import items from '../items.json';
import type { Item } from '../types';

type Config = {
  itemCount: number;
  showCounter: boolean;
  lazyImages: boolean;
};

export const ItemList = component$<{ config: Config }>(({ config }) => {
  const visible = (items as Item[]).slice(0, config.itemCount);
  return (
    <ul>
      {visible.map((item, i) => (
        <ItemCard
          key={item.id}
          item={item}
          showCounter={config.showCounter}
          lazy={config.lazyImages && i >= 6}
        />
      ))}
    </ul>
  );
});

// apps/vite-react/src/components/ItemList.tsx
// components/ItemList.tsx
import allItems from '../items.json';
import { ItemCard } from './ItemCard';
import type { Item } from '../types';

type Config = {
  itemCount: number;
  showCounter: boolean;
  lazyImages: boolean;
};

export function ItemList({ config }: { config: Config }) {
  const items = (allItems as Item[]).slice(0, config.itemCount);
  return (
    <ul>
      {items.map((item, i) => (
        <ItemCard
          key={item.id}
          item={item}
          showCounter={config.showCounter}
          lazy={config.lazyImages && i >= 6}
        />
      ))}
    </ul>
  );
}
