// apps/astro/src/components/Counter.tsx
// src/components/Counter.tsx
import { useState } from 'react';

export function Counter() {
  const [count, setCount] = useState(0);
  return (
    <div className="counter">
      <button onClick={() => setCount(c => Math.max(0, c - 1))}>−</button>
      <span>{count}</span>
      <button onClick={() => setCount(c => c + 1)}>+</button>
    </div>
  );
}

// apps/qwik/src/components/Counter.tsx
import { component$, useSignal } from '@builder.io/qwik';

export const Counter = component$(() => {
  const count = useSignal(0);
  return (
    <div class="counter">
      <button onClick$={() => count.value = Math.max(0, count.value - 1)}>−</button>
      <span>{count.value}</span>
      <button onClick$={() => count.value += 1}>+</button>
    </div>
  );
});
