// apps/astro/src/components/SearchInput.tsx
// src/components/SearchInput.tsx
import { useState, useMemo } from 'react';
import allItems from '../items.json';
import type { Item } from '../types';

type Props = {
  lazyImages: boolean;
};

export function SearchInput({ lazyImages }: Props) {
  const [query, setQuery] = useState('');

  const filtered = useMemo<Item[]>(
    () => (allItems as Item[]).filter(item =>
      item.title.toLowerCase().includes(query.toLowerCase())
    ),
    [query]
  );

  return (
    <>
      <input
        type="search"
        placeholder="Suche..."
        value={query}
        onChange={(e) => setQuery(e.target.value)}
      />
      <p>{filtered.length} Items</p>
      <ul>
        {filtered.map((item, i) => (
          <li key={item.id} className="card">
            <img
              src={item.imageUrl}
              alt={item.title}
              width={400}
              height={300}
              loading={lazyImages && i >= 6 ? 'lazy' : 'eager'}
            />
            <h2>{item.title}</h2>
            <p className="desc">{item.description}</p>
            <span className="price">{item.price}</span>
          </li>
        ))}
      </ul>
    </>
  );
}

// apps/qwik/src/components/SearchInput.tsx
import { component$, useSignal, useComputed$ } from '@builder.io/qwik';
import { ItemCard } from './ItemCard';
import allItems from '../items.json';
import type { Item } from '../types';

export const SearchInput = component$<{ lazyImages: boolean }>(({ lazyImages }) => {
  const query = useSignal('');

  const filtered = useComputed$(() =>
    (allItems as Item[]).filter(item =>
      item.title.toLowerCase().includes(query.value.toLowerCase())
    )
  );

  return (
    <>
      <input
        type="search"
        placeholder="Suche..."
        value={query.value}
        onInput$={(e) => query.value = (e.target as HTMLInputElement).value}
      />
      <p>{filtered.value.length} Items</p>
      <ul>
        {filtered.value.map((item, i) => (
          <ItemCard
            key={item.id}
            item={item}
            showCounter={false}
            lazy={lazyImages && i >= 6}
          />
        ))}
      </ul>
    </>
  );
});
